### ISSUE TITLE
编译报错 dpkg-deb: error: '/tmp/camera_engine_rkaiq_rk3588_5.0_4.1_arm64.deb' is not a Debian format archive

### ISSUE THREAD

**Issue by fqfqngxhs** [erd-yunmu/ubuntu-22.04#1]
我的系统为ubuntu20.04，按照readme步骤编译，安装完依赖，执行  ./build.sh --board=lubancat-4 --so 编译报错如下：
dpkg-deb: error: '/tmp/camera_engine_rkaiq_rk3588_5.0_4.1_arm64.deb' is not a Debian format archive
dpkg: error processing archive /tmp/camera_engine_rkaiq_rk3588_5.0_4.1_arm64.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2
dpkg-deb: error: '/tmp/camera_engine_rkisp-v2.2.0_arm64.deb' is not a Debian format archive
dpkg: error processing archive /tmp/camera_engine_rkisp-v2.2.0_arm64.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2
dpkg-deb: error: '/tmp/fire_config_special_1.2.2_arm64.deb' is not a Debian format archive
dpkg: error processing archive /tmp/fire_config_special_1.2.2_arm64.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2
dpkg-deb: error: '/tmp/rktoolkit_1.0.0-1_arm64.deb' is not a Debian format archive
dpkg: error processing archive /tmp/rktoolkit_1.0.0-1_arm64.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 /tmp/camera_engine_rkaiq_rk3588_5.0_4.1_arm64.deb
 /tmp/camera_engine_rkisp-v2.2.0_arm64.deb
 /tmp/fire_config_special_1.2.2_arm64.deb
 /tmp/rktoolkit_1.0.0-1_arm64.deb
Error: in ./scripts/build-rootfs.sh on line 191
Error: in ./build.sh on line 167

**Comment by erd-yunmu** [comment]
请在当前执行`git lfs fetch && git lfs checkout`再重新编译
